services:
  nobarfilm:
    container_name: nobarfilm
    image: ridhoarmand/nobarfilm:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_COOKIE_DOMAIN=.idho.eu.org

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:3000', (res) => { process.exit(res.statusCode < 400 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true